/* Mapa témat Daniných skript (Zdravotníci s.r.o.) po nadpisech.
   p = strana, h = téma, k = regulární výraz, který musí najít aspoň jedna otázka nebo kartička.
   Kontroluje to tools/check.js — nenajde-li téma, nahlásí ho jako nepokryté. */
window.COVERAGE = [
  { p: 3, h: 'Zákon 258/2000 Sb. — co upravuje', k: 'soustavu orgánů ochrany' },
  { p: 3, h: '§ 8 definice zotavovací akce', k: '30 a více' },
  { p: 3, h: '§ 8 hygienické požadavky pořadatele', k: 'zásobování (pitnou )?vodou' },
  { p: 3, h: '§ 8 ohlášení měsíc předem', k: 'jeden měsíc|1 měsíc' },
  { p: 3, h: '§ 9 zdravotní způsobilost a očkování dětí', k: 'očkov' },
  { p: 3, h: '§ 9 bez akutního onemocnění', k: 'akutního onemocnění' },
  { p: 3, h: '§ 9 14 dnů bez kontaktu s infekcí', k: '14 kalendářních|14 dn' },
  { p: 3, h: '§ 9 posudek praktického lékaře, platnost 2 roky', k: 'dva roky|2 roky' },
  { p: 3, h: '§ 10 zdravotní způsobilost dozoru a zdravotníka', k: 'dospělých osob činných' },
  { p: 3, h: '§ 10 stravování — činnosti epidemiologicky závažné', k: 'potravinářství|potravinářsk' },
  { p: 4, h: '§ 11 kdo je způsobilá osoba (zdravotník)', k: 'třetího ročníku' },
  { p: 4, h: '§ 11 vracení posudků', k: 'vracejí' },
  { p: 4, h: '§ 11 lékárnička podle druhu akce', k: 'minimální rozsah vybavení' },
  { p: 4, h: '§ 11 deník a uchování 6 měsíců', k: '6 měsíců' },
  { p: 4, h: 'Vyhláška 106/2001 Sb. — co upravuje', k: 'hygienické požadavky na zotavovací akce' },
  { p: 4, h: 'Přílohy vyhlášky 1–4', k: 'vzor posudku' },
  { p: 5, h: 'Zdravotnický deník — obsah zápisu', k: 'podpis zdravotníka' },
  { p: 5, h: 'Oznámení kontaktu s infekcí rodičům', k: 'kontakt dítěte s infekcí|kontaktu s infekcí' },
  { p: 5, h: 'Předání lékařských zpráv', k: 'lékařské zprávy' },
  { p: 5, h: 'Zdravotník dohlíží na hygienu, stravu a zátěž', k: 'přiměřeně věku' },
  { p: 5, h: 'Jmenný seznam a místní praktický lékař', k: 'místní praktický lékař' },
  { p: 5, h: 'Zdravotní doklady při odjezdu', k: 'zdravotní pojišťovny' },
  { p: 5, h: 'Převzetí chronických léků', k: 'chronické léky' },
  { p: 5, h: 'Kontrola po příjezdu', k: 'zdravotnický filtr' },
  { p: 5, h: 'Uzamykatelná skříň na léky', k: 'uzamykateln' },
  { p: 5, h: 'Porady s vedoucími a jídelníček', k: 'jídelníčk|jídelní' },
  { p: 5, h: 'Vzdálení zdravotníka z akce', k: 'informovat vedoucího' },
  { p: 5, h: 'Ošetřovna a izolace', k: 'mimo ubytovací prostory' },
  { p: 5, h: 'Ordinační hodiny', k: 'ordinační hodiny' },
  { p: 6, h: 'Lékárnička I. léčivé přípravky', k: 'antiemetik' },
  { p: 6, h: 'Lékárnička II. obvazový materiál', k: 'škrtící pryžové' },
  { p: 6, h: 'Lékárnička III. různé', k: 'zavírací špendlíky' },
  { p: 6, h: 'Zdravotnická etika', k: 'mlčenlivost' },
  { p: 6, h: 'Péče o nemocné', k: 'příjmu a výdeje tekutin' },
  { p: 7, h: 'Hygiena — definice', k: 'zdravém způsobu života' },
  { p: 7, h: 'Epidemiologie — definice', k: 'šířením nákaz|šíření nákaz' },
  { p: 7, h: 'Orgány ochrany veřejného zdraví', k: 'hlavním hygienikem' },
  { p: 7, h: 'Pracovníci státního zdravotního dozoru', k: 'služebním průkazem' },
  { p: 7, h: 'Pravomoc ukončit akci', k: 'akci ukončit|ukončit zotavovací' },
  { p: 7, h: 'Kůže a kožní film', k: 'kožní film' },
  { p: 7, h: 'Mytí rukou', k: 'zápěstí' },
  { p: 7, h: 'Péče o chrup', k: 'paradentóz' },
  { p: 7, h: 'Denní režim a spánek', k: '11 hodin' },
  { p: 8, h: 'Hygienické požadavky ve třech bodech', k: 'pravidelnost činností' },
  { p: 8, h: 'Hygiena výživy', k: 'chemické ani biologické' },
  { p: 8, h: 'Základní živiny', k: 'bílkoviny, tuky a cukry' },
  { p: 8, h: 'Ochranné látky', k: 'vitamíny a minerály' },
  { p: 8, h: 'Rizikové výživové faktory', k: 'nadměrné solení' },
  { p: 8, h: 'Doporučení o výživě', k: 'celozrnn' },
  { p: 8, h: 'Režim stravování', k: 'ne delšími než 3' },
  { p: 8, h: 'Stravovací služby, vyhláška 137/2004', k: '137/2004' },
  { p: 8, h: 'Členění stravovacího provozu', k: 'skladovací a provozní' },
  { p: 9, h: 'Zabezpečení provozu stravování, provozní řád', k: 'provozní řád' },
  { p: 9, h: 'Zákaz syrových vajec a masa', k: 'neopracovaných vajec' },
  { p: 9, h: 'Infekce — definice', k: 'tkáně hostitele' },
  { p: 9, h: 'Čtyři stadia infekčního onemocnění', k: 'prodromální' },
  { p: 9, h: 'Přímý a nepřímý přenos', k: 'nepřímý' },
  { p: 9, h: 'Vnímavost a očkování', k: 'vnímavost' },
  { p: 9, h: 'Dezinfekce', k: 'doba působení|doby působení' },
  { p: 10, h: 'Sterilizace', k: 'sterilizace' },
  { p: 10, h: 'Léčivo a expirace', k: 'expirac' },
  { p: 10, h: 'Lékové formy', k: 'SUPP' },
  { p: 10, h: 'Způsoby podání', k: 'do svalu' },
  { p: 10, h: 'Lékové skupiny', k: 'hemostatika' },
  { p: 11, h: 'První pomoc — definice', k: 'naučená opatření' },
  { p: 11, h: 'Povinnost poskytnout PP a § 150', k: '§ 150' },
  { p: 11, h: 'Zdravotnická a technická první pomoc', k: 'technická' },
  { p: 11, h: 'Základní a rozšířená první pomoc', k: 'rozšířen' },
  { p: 11, h: 'IZS a tísňová čísla', k: '158' },
  { p: 11, h: 'Aplikace Záchranka', k: 'Záchranka' },
  { p: 12, h: 'TAPP a TANR', k: 'TANR' },
  { p: 12, h: 'Postup na místě události', k: 'koho mám k dispozici' },
  { p: 12, h: 'Prvotní vyšetření', k: 'masivní krvácení' },
  { p: 12, h: 'Následné vyšetření', k: 'od hlavy k patě' },
  { p: 12, h: 'Anamnéza AA, FA, OA, NO', k: 'farmakologick' },
  { p: 12, h: 'Pohled, poslech, pohmat, poklep', k: 'poklep' },
  { p: 13, h: 'TK, GLY, TT', k: 'glykemie' },
  { p: 13, h: 'Další vyšetřovací metody', k: 'RTG' },
  { p: 13, h: 'Bezpečnost zachránce', k: 'vlastní bezpečnost' },
  { p: 13, h: 'Zásady prevence úrazů', k: 'ješitnost' },
  { p: 13, h: 'Třídění zraněných — triage', k: 'triage' },
  { p: 13, h: 'Pravidlo START a jeho cíl', k: 'pravidl[oa] START' },
  { p: 13, h: 'Rány vnější a vnitřní', k: 'vnější' },
  { p: 13, h: 'Rány podle vzniku', k: 'sečné' },
  { p: 14, h: 'Základní toaleta rány', k: 'sutura' },
  { p: 14, h: 'Znečištěné rány', k: 'štěrk' },
  { p: 14, h: 'Cizí těleso v ráně', k: 'zaklíněn' },
  { p: 14, h: 'Amputace', k: 'amputát' },
  { p: 14, h: 'Skalpace', k: 'skalpace' },
  { p: 14, h: 'Hmyzí bodnutí', k: 'žihadl' },
  { p: 14, h: 'Rány pokousáním', k: 'pokousání' },
  { p: 14, h: 'Uštknutí hadem', k: 'uštknutí' },
  { p: 14, h: 'Klíšťata', k: 'klíště' },
  { p: 14, h: 'Kontrola ran a převazy', k: 'převazy' },
  { p: 15, h: 'Druhy krvácení', k: 'vlásečnicov' },
  { p: 15, h: 'Tepenné krvácení', k: 'vystřikuj' },
  { p: 15, h: 'Krvácení na krku — vzduchová embolie', k: 'embolii' },
  { p: 15, h: 'Žilní krvácení', k: 'žilní' },
  { p: 15, h: 'Vlásečnicové krvácení — mašlička, strip', k: 'mašlička' },
  { p: 15, h: 'Krvácení z nosu', k: 'nosní skořepy' },
  { p: 16, h: 'Krvácení ze zvukovodu', k: 'zvukovodu' },
  { p: 16, h: 'Krvácení z dutiny ústní', k: 'skousnout' },
  { p: 16, h: 'Zvracení krve', k: 'hematemez' },
  { p: 16, h: 'Vykašlávání krve', k: 'hemoptýz' },
  { p: 16, h: 'Krvácení z močových cest', k: 'močových cest' },
  { p: 16, h: 'Krvácení z konečníku', k: 'hemoroid' },
  { p: 16, h: 'Krvácení z pohlavních orgánů', k: 'pohlavních orgánů' },
  { p: 16, h: 'Zásady u ran a krvácení', k: 'nevytahovat předmět' },
  { p: 17, h: 'Obvazy podle funkce', k: 'korekční' },
  { p: 17, h: 'Obvazy podle materiálu', k: 'zinkoklihov' },
  { p: 18, h: 'Šátkové obvazy', k: 'rovnoramenného' },
  { p: 18, h: 'Obinadlové obvazy', k: 'obinadlov' },
  { p: 18, h: 'Natažení, natržení, přetržení', k: 'natržení' },
  { p: 18, h: 'Zhmoždění kloubu', k: 'kontuze' },
  { p: 18, h: 'Podvrtnutí', k: 'distorze' },
  { p: 18, h: 'Vymknutí', k: 'luxace' },
  { p: 19, h: 'Zlomeniny — dělení a příznaky', k: 'otevřené' },
  { p: 19, h: 'Podle pozice úlomků', k: 'dislokovan' },
  { p: 19, h: 'Podle linie lomu', k: 'spirálov' },
  { p: 19, h: 'Podle mechanismu', k: 'impresivní' },
  { p: 19, h: 'Podle vzniku', k: 'patologick' },
  { p: 19, h: 'První pomoc u zlomenin', k: 'mezi dvěma klouby' },
  { p: 20, h: 'Odhad krevních ztrát', k: 'pánev' },
  { p: 20, h: 'Penetrující poranění břicha', k: 'penetrující' },
  { p: 20, h: 'Nepenetrující poranění břicha', k: 'prkenovit|prknovit' },
  { p: 20, h: 'Spolknutí cizího tělesa', k: 'spolkl' },
  { p: 20, h: 'Průjem', k: 'Endiaron' },
  { p: 21, h: 'Zánět slepého střeva', k: 'slepého střeva' },
  { p: 21, h: 'Zánět žlučníku', k: 'žlučník' },
  { p: 21, h: 'Zánět slinivky', k: 'slinivk' },
  { p: 21, h: 'Zánět pobřišnice', k: 'pobřišnic' },
  { p: 21, h: 'Vředová choroba', k: 'vřed' },
  { p: 22, h: 'Střevní neprůchodnost', k: 'ileu' },
  { p: 22, h: 'Ledvinová kolika', k: 'kolika' },
  { p: 22, h: 'Akutní koronární syndrom', k: 'koronární' },
  { p: 22, h: 'Infarkt myokardu', k: 'infarkt' },
  { p: 23, h: 'Vdechnutí cizího tělesa', k: 'Heimlich' },
  { p: 23, h: 'Astma bronchiale', k: 'astma' },
  { p: 23, h: 'Zánět hrtanu', k: 'hrtanu' },
  { p: 23, h: 'Cévní mozková příhoda', k: 'CMP' },
  { p: 24, h: 'CMP — iktové centrum do 3 hodin', k: 'iktové' },
  { p: 24, h: 'Epilepsie — příčiny', k: 'genetik' },
  { p: 24, h: 'Petit mal a grand mal', k: 'grand mal' },
  { p: 24, h: 'Status epilepticus', k: 'status epilepticus' },
  { p: 24, h: 'Co při záchvatu nedělat', k: 'jazyk' },
  { p: 24, h: 'Febrilní křeče', k: 'febriln' },
  { p: 25, h: 'Cukrovka I. a II. typu', k: 'dependentní' },
  { p: 25, h: 'Hypoglykemie', k: 'hypoglykemi' },
  { p: 25, h: 'Hyperglykemie', k: 'hyperglykemi' },
  { p: 25, h: 'Glukagon a inzulinová pumpa', k: 'glukagon' },
  { p: 25, h: 'Alergická reakce a Epipen', k: 'Epipen' },
  { p: 25, h: 'Poruchy vědomí', k: 'sopor' },
  { p: 25, h: 'Glasgow Coma Scale', k: 'GCS' },
  { p: 26, h: 'Bezvědomí — příčiny', k: 'uremické' },
  { p: 26, h: 'Mdloba', k: 'vazovagáln' },
  { p: 26, h: 'Postup při bezvědomí', k: 'bolestivý podnět' },
  { p: 26, h: 'Šok — definice', k: 'kolující tekutiny' },
  { p: 26, h: 'Fáze šoku', k: 'dekompenzovan' },
  { p: 26, h: 'Druhy šoku', k: 'obstrukční' },
  { p: 26, h: 'Příznaky šoku', k: 'nitkovit' },
  { p: 27, h: 'Pravidlo 5T', k: '5T' },
  { p: 27, h: 'Poranění hrudníku, blast syndrom', k: 'blast' },
  { p: 27, h: 'Paradoxní dýchání', k: 'paradoxní' },
  { p: 27, h: 'Pneumotorax', k: 'pneumotorax' },
  { p: 27, h: 'Typy pneumotoraxu', k: 'ventilov' },
  { p: 28, h: 'Srdeční tamponáda', k: 'tamponáda' },
  { p: 28, h: 'Aneurysma a ruptura aorty', k: 'aort' },
  { p: 28, h: 'Úpal', k: 'úpal' },
  { p: 28, h: 'Úžeh', k: 'úžeh' },
  { p: 28, h: 'Podchlazení', k: 'podchlazení' },
  { p: 29, h: 'Omrzliny', k: 'omrzlin' },
  { p: 29, h: 'Úraz elektrickým proudem', k: 'nejmenšího odporu' },
  { p: 29, h: 'Poleptání', k: 'poleptání' },
  { p: 29, h: 'Popáleniny', k: 'popálenin' },
  { p: 30, h: 'Pravidlo devíti', k: 'pravidl[ao] devíti' },
  { p: 30, h: 'Palmární pravidlo u dětí', k: 'palmární' },
  { p: 30, h: 'Toxikologické informační středisko', k: '224 919 293' },
  { p: 30, h: 'Vstup jedu do těla', k: 'transdermáln' },
  { p: 30, h: 'Příčiny a příznaky otrav', k: 'sebevražedn' },
  { p: 30, h: 'Otrava alkoholem', k: 'otrav[ay] alkoholem' },
  { p: 30, h: 'Otrava oxidem uhelnatým', k: 'oxid uhelnat|oxidem uhelnat' },
  { p: 31, h: 'Otrava organofosfáty', k: 'organofosf' },
  { p: 31, h: 'Otrava léky a drogami', k: 'plata' },
  { p: 31, h: 'Otrava houbami', k: 'muchomůrka' },
  { p: 31, h: 'Tonutí — čísla', k: '40 %' },
  { p: 31, h: 'Vlhké a suché tonutí', k: 'laryngospasm' },
  { p: 31, h: 'Aktivní a pasivní tonoucí', k: 'pasivní tonoucí' },
  { p: 32, h: 'Technická první pomoc u tonutí', k: 'plavčík' },
  { p: 32, h: 'Zdravotnická první pomoc u tonutí', k: 'pěti vdechy|5 vdech|5 úvodní' },
  { p: 32, h: 'Zlomenina klenby lební', k: 'klenby' },
  { p: 32, h: 'Zlomenina spodiny lebeční', k: 'brýlový' },
  { p: 32, h: 'Otřes mozku', k: 'otřes' },
  { p: 32, h: 'Zhmoždění mozku', k: 'zhmoždění mozku' },
  { p: 32, h: 'Komprese mozku', k: 'komprese mozku' },
  { p: 32, h: 'Epidurální krvácení', k: 'epidurální' },
  { p: 33, h: 'Subdurální krvácení', k: 'subdurální' },
  { p: 33, h: 'Subarachnoideální krvácení', k: 'subarachnoide' },
  { p: 33, h: 'Poranění páteře a míchy', k: 'míchy' },
  { p: 33, h: 'Spinální šok', k: 'spinální šok' },
  { p: 33, h: 'Příčiny poranění páteře', k: '24 %' },
  { p: 33, h: 'Příznaky poranění míchy', k: 'svěrač' },
  { p: 33, h: 'První pomoc — nehýbat', k: 'nehýbat|NEHÝBEJTE' },
  { p: 33, h: 'Transportní polohy a manipulace', k: 'manipul' },
  { p: 34, h: 'Neodkladná resuscitace — definice', k: 'okysličené krve' },
  { p: 34, h: 'Základní KPR — ABCD', k: 'Airway' },
  { p: 34, h: 'Rozšířená KPR — DEFGHI', k: 'Gauging' },
  { p: 34, h: 'AED', k: 'AED' },
  { p: 34, h: 'Vyšetření a záklon hlavy', k: 'gasping' },
  { p: 34, h: 'KPR dospělého', k: '30 : 2' },
  { p: 35, h: 'KPR dětí', k: '15 : 2' },
  { p: 35, h: 'KPR novorozence', k: '3 : 1' },
  { p: 35, h: 'Jak dlouho resuscitovat', k: 'vyčerpání' },
  { p: 35, h: 'Kdy KPR nezahajujeme', k: 'známky smrti' },
  { p: 36, h: 'Chyby při KPR', k: 'déle než 10 sekund' },
  { p: 36, h: 'Záklon hlavy', k: 'záklon' },
  { p: 36, h: 'Zotavovací poloha', k: 'zotavovací' },
  { p: 36, h: 'Protišoková poloha', k: 'protišokov' }
];
